### PR TITLE
feat: add filterQuality

### PR DESCRIPTION
**Pull request by abichinger**
exposes [filterQuality](https://api.flutter.dev/flutter/widgets/Image/filterQuality.html) of `Image`

My use case:
I want to set `filterQuality` to `FilterQuality.none`, when cropping pixel art. Otherwise the pixel art is blurred.

### CODE REVIEW

**Comment by chooyan-eng** [comment]
@abichinger Thank you for this pull request as well! I'm thinking of not just adding `filterQuality` to `Crop` argument but introducing `imageWidgetBuilder` like below.

```dart
Crop(
  imageWidgetBuilder: (BuildContext context, Uint8List imageData) {
    return Image.memory(
      imageData,
      fit: BoxFit.contain,
      // users don't need to indicate width and height explicitly here.
      filterQuery: FilterQuality.none,
      // and whatever params and widgets you want...
    );
  },
),
```

This will enable you to composite widgets more flexibly. What do you think of this?

**Comment by abichinger** [comment]
@chooyan-eng I like your approach. I'm sure it will cover more use cases! :+1:

**Comment by chooyan-eng** [comment]
@abichinger Can you update this pull request with that idea? Or should I make another pull request to address this?

**Comment by abichinger** [comment]
@chooyan-eng I can update it.

**Comment by abichinger** [comment]
@chooyan-eng After playing around with the idea, I'm not convinced anymore. I think only adding `filterQuality` is the better solution.

Here are my concerns regarding `imageWidgetBuilder`:

```dart
// A user could add a Padding around the image. The result is that the preview is missaligned with the actual crop. 
Crop(
  imageBuilder: (context, imageData) {
    return Padding(
      padding: const EdgeInsets.all(0),
      child: Image.memory(
        imageData,
        fit: BoxFit.contain,
        filterQuality: FilterQuality.none,
      ),
    );
  },
),

// The user could apply some filters to the image widget, but the filters won't be applied to the cropped image.
Crop(
  imageWidgetBuilder: (context, imageData) {
    return ColorFiltered(
      colorFilter: ColorFilter.mode(
        Colors.grey,
        BlendMode.saturation,
      ),
      child: Image.memory(
        imageData,
        fit: BoxFit.contain,
        filterQuality: FilterQuality.none,
      ),
    );
  },
),
```

So the issue with `imageWidgetBuilder` is that the preview can be different from the image data returned by `onCropped`.

**Comment by abichinger** [comment]
> Can you just add filterQuality argument to Crop?

Done.

**Review by chooyan-eng — APPROVED** [review]
@abichinger Thank you for updating! I'll merge this.

**Pull request merged**
