### PR TITLE
feat: add overlay builder

### PR DESCRIPTION
**Pull request by abichinger**
Hey!

Thank you for sharing this awesome crop widget.

I added a builder function to add a custom overlay to the clipping area.
image

Resolves: #86

### CODE REVIEW

**Comment by chooyan-eng** [comment]
@abichinger Hi, I'm really sorry that I left this PR without any reaction. This PR looks great and can you migrate the same one to the current source code? Currently, `_rect` is equivalent to `_readyState.cropRect`.

And my suggestion is that we don't need to pass `context` and `radius` as builder's arguments because both are relevantly available at the user's side, meaning that they may not have motivation to use the given one. 

If you don't seem to watch this repository anymore, I'll finish this PR by myself and merge it. Thanks.

**Comment by abichinger** [comment]
@chooyan-eng Hi, I'm going to update this PR.

**Comment by abichinger** [comment]
I rebased the PR and added linux support to the example

> And my suggestion is that we don't need to pass `context` and `radius` as builder's arguments because both are relevantly available at the user's side, meaning that they may not have motivation to use the given one.

I removed `radius`, but I kept the `context`, because I think it is common practice in Flutter to pass the `BuildContext` to a "builder function" (see [`WidgetBuilder`](https://api.flutter.dev/flutter/widgets/WidgetBuilder.html))

**Review by chooyan-eng — APPROVED** [review]
@abichinger Looks great to me! thanks!

**Pull request merged**
