### PR TITLE
Update image package version to 4.0.6

### PR DESCRIPTION
**Pull request by ravikant-paudel**
This PR consist fix for #83

### CODE REVIEW

**Comment by ravikant-paudel** [comment]
cc @chooyan-eng

**Review by Bikash-Giri — APPROVED** [review]

**Review by ashim-upadhaya — APPROVED** [review]

**Review by biplab-khalti — APPROVED** [review]

**Review by Kingtous — APPROVED** [review]

**Review by sarbagyastha — APPROVED** [review]
LGTM

**Comment by JeromeGsq** [comment]
LGTM too

**Comment by ashim-upadhaya** [comment]
Merge IT

**Comment by JeromeGsq** [comment]
Hi @ravikant-paudel, 
Is the work on this RP completed or do you have any other changes to make? 
I'd like to test my code with this fix to make sure the bug is fixed on my end. 
Thanks

**Comment by ravikant-paudel** [comment]
Hello @JeromeGsq ,
it is working fine on my side.
If you find any bug. please let me know.
Thanks

**Comment by ravikant-paudel** [comment]
hi @chooyan-eng Please review my PR
Thanks

**Review by rickypid — APPROVED** [review]
Hello @chooyan-eng  ,
it is working fine on my side.
Thanks

**Comment by chooyan-eng** [comment]
Thank you for the issue and PR here.
I'll check this and update the package today.

**Comment by chooyan-eng** [comment]
LGTM!

@ravikant-paudel 
Thank you for making this PR.

@sarbagyastha @JeromeGsq @ashim-upadhaya @rickypid 
Thank you all for checking the PR and sorry for making you wait merging and updating. 
This fix would be releases as `0.7.4` soon.

**Pull request merged**
